apply plugin: 'com.android.library'
def AAVersion = '3.3.2'

android {
    compileSdkVersion 25
    defaultConfig {
        minSdkVersion 14
        targetSdkVersion 21
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [ androidManifestFile: file('src/main/AndroidManifest.xml').absolutePath ]
            }
        }
    }
}
dependencies {
    // compile files('libs/androidannotations-api-2.7.jar')
    implementation files('libs/dashclock-api-r1.1.jar')
    //implementation files('libs/nineoldandroids-2.4.0.jar')
    annotationProcessor "org.androidannotations:androidannotations:$AAVersion"
    implementation "org.androidannotations:androidannotations-api:$AAVersion"
    implementation 'com.android.support:support-v4:25.3.1'
    implementation 'com.android.support:appcompat-v7:25.3.1'
    api 'com.github.flavienlaurent.datetimepicker:library:+'
    implementation 'com.android.support:design:25.3.1'
    implementation 'com.github.mfornos:humanize-slim:1.2.2'
    implementation 'com.github.AndroidDeveloperLB:MaterialPreferenceLibrary:5'
}
