apply plugin: 'com.android.application'

android {
    compileSdkVersion 25

    defaultConfig {
        applicationId "com.icechen1.notable"
        minSdkVersion 14
        targetSdkVersion 21
    }
    buildTypes {
        debug {
            // Install alongside an existing release build by using a different applicationId
            applicationIdSuffix ".debug"
        }

        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
}

dependencies {
    implementation project(':notableLibrary')
}
